general.import = [ "~/.config/omarchy/current/theme/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "JetBrainsMono Nerd Font" }
bold = { family = "JetBrainsMono Nerd Font" }
italic = { family = "JetBrainsMono Nerd Font" }
size = 15

[window]
padding.x = 2
padding.y = 2
decorations = "None"

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]
